[workspace]
resolver = "3"
members = [
    "dependency-factory",
    "dependency-factory-derive",
    "xtask",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jeffparsons/dependency-factory"
authors = ["Jeff Parsons"]
